@startuml class Diagram
class Usuario {
  + id: int
  + nome: string
  + email: string
  + telefone: string
}

class Chamado {
  + id: string
  + dataAbertura: datetime
  + solicitante: string
  + solicitacao: string
  + status: string
  + senhaConsulta: string
  + resumo: string
}

class Atividade {
  + id: int
  + tipo: enum (presencial, remota)
  + status: string
  + dataInicio: datetime
  + dataFim: datetime
}

class Fila {
  + id: int
  + nome: string
  + tipo: enum (sistema, triagem, acompanhamento)
}

class Servico {
  + id: int
  + nome: string
  + status: string
  + quantidade: int
  + unidadeMedida: string (opcional)
  + preco: decimal
}

class Log {
  + id: int
  + dataHora: datetime
  + descricao: string
  + usuario: string
}

class Equipamento {
    + id: int
    + numeroSerie: string
    + numeroPatrimonio: string
    + descricao: string
}

class Inservivel {
    + id: int
    + equipamentoId: int
    + dataInservivel: datetime
}

Chamado "1" -- "*" Atividade : possui
Atividade "*" -- "1..*" Servico : realiza
Fila "*" -- "*" Atividade : gerencia
Chamado "*" -- "1" Usuario : solicita
Atividade "*" -- "1" Usuario : atribuido
Chamado "*" -- "1" Equipamento : relacionado
Equipamento "1" -- "0..1" Inservivel : marcado
Usuario "*" -- "*" Log : gera
@enduml