@startuml ticket States
[*] --> Aberto : Chamado criado
Aberto --> Triagem : Chamado atribuído à triagem
Triagem --> EmAndamento : Triagem concluída
EmAndamento --> EmEspera : Aguardando informações
EmAndamento --> Concluido : Chamado concluído com sucesso
EmEspera --> EmAndamento : Informações fornecidas
Concluido --> Reaberto : Reabertura do chamado
Concluido --> [*] : Descarte
Reaberto --> Triagem : Chamado reaberto, passa pela triagem
@enduml